baseURL = "https://gexue.dev/"
languageCode = "zh-cn"
title = "割雪 | Gexue"
theme = "PaperMod"

paginate = 20

enableRobotsTXT = true
enableEmoji = true

[params]
mainSections = ["devlog"]
defaultTheme = "dark"
disableThemeToggle = true
description = "这里是割雪的个人网站，一个独立游戏开发者的创作空间。分享游戏设计、开发日志与个人思考。"
author = "割雪"
showReadingTime = true
showShareButtons = false
showPostNavLinks = true
showBreadCrumbs = false
showCodeCopyButtons = true
showRssButtonInSectionTermList = false
showWordCount = false

displayFullLangName = true
ShowToc = true

[params.homeInfoParams]
Title = "割雪"
Content = "独立游戏开发者。\n\n目前正在学习绘画、Godot 与游戏设计。\n\n记录开发日志与创作过程。\n\n\n\n联系我们：\n\n邮箱：mail@gexue.dev"

[frontmatter]
date = ["date", "publishDate", "lastmod"]

[[menu.main]]
identifier = "devlog"
name = "开发日志"
url = "/devlog/"
weight = 10

[[menu.main]]
identifier = "bilibili"
name = "bilibili"
url = "https://space.bilibili.com/18497689"
weight = 20